Feat: Structure MVC
yoanbernabeu/Roadmap-Dev-Symfony pull request #96
Opened 2021-11-16 09:06 UTC by David-Moisan

2021-11-16 09:22 UTC, David-Moisan commented
@yoanbernabeu  j'ai mis les bases de Symfony en 4è position, mais évidemment c'est provisoire en attendant un meilleur tri des différents modules.

2021-11-16 13:39 UTC, divinoPV approved these changes

2021-11-18 07:45 UTC, yoanbernabeu commented
@David-Moisan et @divinoPV : Merci pour vos contributions ?
Je vous laisse régler les conflits avant de merger dans main ?

2021-11-27 23:46 UTC, yoanbernabeu requested changes
Hello, est-ce que tu peux résoudre les conflits avant que je merge ?

2021-11-28 05:44 UTC, David-Moisan commented
@yoanbernabeu  je n'avais pas fait gaffe pour le conflit j'ai régler ça et j'attend que tu merge pour envoyer une autre PR :)

2021-11-28 09:36 UTC, yoanbernabeu commented
Merci pour toutes tes modifications.
Hélas, la structure des répertoires à changer depuis (désole..)

Est-ce que tu peux rafraichir ton dépôt, et adapter tes modifications à la nouvelle arborescence ?

2021-11-28 09:38 UTC, yoanbernabeu requested changes
Merci pour toutes tes modifications.
Hélas, la structure des répertoires à changer depuis (désole..)

Est-ce que tu peux rafraichir ton dépôt, et adapter tes modifications à la nouvelle arborescence ?

2021-11-28 09:38 UTC, yoanbernabeu commented
> @yoanbernabeu je n'avais pas fait gaffe pour le conflit j'ai régler ça et j'attend que tu merge pour envoyer une autre PR :)

Merci pour le taf <3

2021-11-29 15:47 UTC, closed without merging