Introduction PHP
yoanbernabeu/Roadmap-Dev-Symfony pull request #98
Opened 2021-11-16 10:48 UTC by maitrepylos

Petite intro à casser

2021-11-16 13:38 UTC, divinoPV requested changes

2021-11-16 13:38 UTC, divinoPV commented on docs/08-php/00-introduction.md
> +Elément d'histoire
```suggestion
Élément d'histoire
```

2021-11-16 13:38 UTC, divinoPV commented on docs/08-php/00-introduction.md
> +savoir qui venait consulter son CV). PHP/FI signifait Personal Home Page Tools / Forms Interpreter.
```suggestion
savoir qui venait consulter son CV). PHP/FI signifiait Personal Home Page Tools / Forms Interpreter.
```

2021-11-16 13:38 UTC, divinoPV commented on docs/08-php/00-introduction.md
> +Petit à pettit, la bibliothèque PERL s’est muée en une implémentation directe en C, afin d’augmenter
```suggestion
Petit à petit, la bibliothèque PERL s’est muée en une implémentation directe en C, afin d’augmenter
```

2021-11-16 13:38 UTC, divinoPV commented on docs/08-php/00-introduction.md
> +apparition, grâce à un « nouveau moteur » PHP (Zend engine 2). Depuis PHP 7 , la sortie d'une
```suggestion
apparition, grâce à un « nouveau moteur » PHP (Zend engine 2). Depuis PHP 7, la sortie d'une
```

2021-11-16 13:38 UTC, divinoPV commented on docs/08-php/00-introduction.md
> +release est régulière. une nouvelle version est sortie chaque année.
```suggestion
release est régulière, chaque année sort une nouvelle version.
```

2021-11-16 13:38 UTC, divinoPV commented on docs/08-php/00-introduction.md
> +* A l’origine, un langage de script pour serveurs web
```suggestion
* À l’origine, un langage de script pour serveurs web
```

2021-11-16 13:38 UTC, divinoPV commented on docs/08-php/00-introduction.md
> +    * A l’origine, PHP était un langage de script conçu spécifiquement pour agir sur les serveurs
```suggestion
    * À l’origine, PHP était un langage de script conçu spécifiquement pour agir sur les serveurs
```

2021-11-16 13:38 UTC, divinoPV commented on docs/08-php/00-introduction.md
> +      libres et gratuites. Le site officiel est http://www.php.net La communauté des développeurs
```suggestion
      libres et gratuites. Le site officiel est http://www.php.net, la communauté des développeurs
```

2021-11-16 13:38 UTC, divinoPV commented on docs/08-php/00-introduction.md
> +      avant d’être exécuté. Mais ce code intermédiaire est recréé à chaque exécurtion et ne peut pas
```suggestion
      avant d’être exécuté. Mais ce code intermédiaire est recréé à chaque exécution et ne peut pas
```

2021-11-16 13:38 UTC, divinoPV commented on docs/08-php/00-introduction.md
> +* D’autres base de données (SQLite, PostgreSQL, Oracle, SqlSrv)‏
```suggestion
* D’autres bases de données (SQLite, PostgreSQL, Oracle, SqlSrv)‏
```

2021-11-16 13:38 UTC, divinoPV commented on docs/08-php/00-introduction.md
> +bases de données, PHP 5 contient des connexions natives vers la plupart des base de données (par
```suggestion
bases de données, PHP 5 contient des connexions natives vers la plupart des bases de données (par
```

2021-11-16 14:26 UTC, maitrepylos commented
Merci   @divinoPV pour la correction :)

2021-11-16 14:29 UTC, maitrepylos commented on docs/08-php/00-introduction.md
> +* A l’origine, un langage de script pour serveurs web
La majuscule avec ou sans accent n'est pas une erreur en soit, il faut juste se mettre d'accord ici ;)

2021-11-18 07:38 UTC, yoanbernabeu approved these changes

2021-11-18 07:38 UTC, merged